version: "3"
services:
  database-portfolio_data:
    container_name: database-portfolio_data
    image: mariadb:latest
    ports:
      - 65050:3306
    volumes:
      - ./back-end_Directus/database:/var/lib/mysql

  cache-portfolio_data:
    container_name: cache-portfolio_data
    image: redis:latest

  directus-portfolio_data:
    container_name: directus-portfolio_data
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./back-end_Directus/directus/uploads:/directus/uploads
      - ./back-end_Directus/directus/database:/directus/database
      - ./back-end_Directus/directus/extensions:/directus/extensions
    depends_on:
      - cache-portfolio_data
      - database-portfolio_data
    restart: unless-stopped
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"

      # DB CONFIGURATION
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: database-portfolio_data
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      REDIS_HOST: cache-portfolio_data
      REDIS_PORT: 6379

      CACHE_STORE: "redis"
      RATE_LIMITER_STORE: "redis"
      SYNCHRONIZATION_STORE: "redis"
      MESSENGER_STORE: "redis"

      # DEFAULT ADMIN USER
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      #WEBSOCKETS
      WEBSOCKETS_ENABLED: "true"
      WEBSOCKETS_REST_ENABLED: "true"
      WEBSOCKETS_REST_AUTH: "handshake"
      WEBSOCKETS_REST_AUTH_TIMEOUT: 15

      #STORAGE
      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./back-end_Directus/uploads"

  nextjs-front-porfolio_data:
    depends_on:
      - directus-portfolio_data
    build: next-client
    ports:
      - 3000:3000
