vich_uploader:
    db_driver: orm

    mappings:
        experiences:
            uri_prefix: /img/experiences
            upload_destination: '%kernel.project_dir%/public/img/experiences'
            namer: Vich\UploaderBundle\Naming\UniqidNamer